# Generated by Django 3.0.4 on 2022-12-06 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0002_entry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='resume',
            field=models.TextField(max_length=200, verbose_name='Resumen'),
        ),
    ]
