# Generated by Django 3.0.3 on 2023-01-06 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0003_auto_20230105_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='resume',
            field=models.CharField(max_length=400, verbose_name='Resumen'),
        ),
    ]
