# Generated by Django 3.2.16 on 2023-01-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrada', '0006_alter_entry_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='resume',
            field=models.CharField(max_length=400, verbose_name='Resumen'),
        ),
    ]
