# Generated by Django 3.0.3 on 2023-01-08 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'ADMINISTRADOR'), ('1', 'USUARIO'), ('2', 'OTRO')], max_length=1),
        ),
    ]
