# Generated by Django 3.0.3 on 2023-01-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230108_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Usuario'), ('O', 'Otro')], max_length=1),
        ),
    ]
